#!/usr/bin/env python3
"""build-model-roster.py — merge the wave manifests into ONE deduplicated roster
for the single locked re-run ("redo the whole list, starting with w1").

Order: wave1 first (the controlled, balanced 25), then wave2's new tags, then
wave3's new tags — grouped by bracket. First occurrence wins (a tag that appears
in several waves is kept once, in the bracket where it first appears). Commented
model lines are skipped; `# bracket:` labels are preserved as group headers.

    python3 scripts/build-model-roster.py            # writes data/models.txt
    python3 scripts/build-model-roster.py --check     # print stats only

The full roster goes through the SAME guard (run.py --preflight + node-power.sh
setup); --rm-after bounds disk; --shuffle decorrelates order. Run wave1
(data/models.txt) first as the audit anchor, then this roster for the rest.
"""
import argparse
import os

SRC = [("w1", "data/legacy/models.legacy-w1.txt"), ("w2", "data/legacy/models.legacy-w2.txt"), ("w3", "data/legacy/models.legacy-w3.txt")]
BRACKET_ORDER = ["0-1B", "1-2B", "2-3B", "3-4B", "4-5GB"]
OUT = "data/models.txt"


def parse(path):
    """Yield (bracket, tag) for each real model line; skip comments + blanks."""
    bracket = None
    for line in open(path):
        s = line.strip()
        if s.startswith("# bracket:"):
            bracket = s.split(":", 1)[1].strip()
            continue
        if not s or s.startswith("#"):
            continue
        yield bracket, s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    seen = {}          # tag -> (bracket, wave) first occurrence
    by_bracket = {b: [] for b in BRACKET_ORDER}
    extra_brackets = {}
    counts = {w: 0 for w, _ in SRC}
    for wave, path in SRC:
        if not os.path.exists(path):
            print(f"WARN: {path} missing, skipping")
            continue
        for bracket, tag in parse(path):
            if tag in seen:
                continue
            seen[tag] = (bracket, wave)
            counts[wave] += 1
            bucket = by_bracket.get(bracket)
            if bucket is None:
                bucket = extra_brackets.setdefault(bracket, [])
            bucket.append((tag, wave))

    total = len(seen)
    print(f"unique tags: {total}  (new per wave: " + ", ".join(f"{w}={n}" for w, n in counts.items()) + ")")
    for b in BRACKET_ORDER:
        print(f"  {b:6}: {len(by_bracket[b])}")
    for b, lst in extra_brackets.items():
        print(f"  {b!r} (non-standard label): {len(lst)}")
    if args.check:
        return

    lines = [
        "# Unified model roster — the FULL deduplicated list for the single locked re-run.",
        "# Generated by scripts/build-model-roster.py from the archived per-list sources in",
        "# data/legacy/ (deduplicated; earlier-list tags lead each bracket).",
        "# Run under the guard: scripts/node-power.sh setup + run.py --preflight (turbo off,",
        "# RAPL package-0, perf on). --rm-after bounds disk; --shuffle decorrelates order.",
        f"# Total unique tags: {total}.",
        "",
    ]
    for b in BRACKET_ORDER + list(extra_brackets):
        bucket = by_bracket.get(b) or extra_brackets.get(b) or []
        if not bucket:
            continue
        lines.append(f"# bracket: {b}")
        lines += [tag for tag, _ in bucket]
        lines.append("")
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"\nwrote {OUT} ({total} tags)")


if __name__ == "__main__":
    main()
